version: '3.8'
services:
  rhean-db:
    image: postgres:16
    container_name: rhean-db-data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=digipg@dm1n
    ports:
      - "6433:5432"
    volumes:
      - rhean-db-data:/var/lib/postgresql/data
    restart: always
  rhean-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rhean-web-data
    depends_on:
      - rhean-db
    ports:
      - "18188:8069"
      - "18187:8072"
    volumes:
      - ./configs/rhean.conf:/etc/odoo/odoo.conf:ro 
      - ./data/odoo/addons:/mnt/extra-addons
      - rhean-web-data:/var/lib/odoo
      - ${BRIQ_SRC}/briq_erp:/mnt/briq_erp
      - ${BRIQ_SRC}/rhean:/mnt/rhean
    restart: always

volumes:
  rhean-db-data:
  rhean-web-data: